# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c86fb43db0253845ff3a56acd0b2904dda2a4acc34e98b9be0f448b3c4c671b32707355e9f547770bb8a0b78a4938f07c01d1d2fa406c09a39e89c957f3d068

test:
  secret_key_base: dbc25ce053fc229a669624a005a5f2ec3b3df740cbbf9d8c490a7b34757ae9e549a603e21a56c7b0a3f8d7a1dc4809f156e949c6e21478690a4d9bd15896f73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
